nohup wget \
-e robots=off \
--no-parent \
--mirror \
--wait=3 \
--random-wait \
--page-requisites \
--convert-links \
--adjust-extension \
--trust-server-names \
--no-verbose \
--retry-on-http-error=408,500,502,503,504 \
--retry-connrefused \
--append-output=wgetlog-takebouki.txt \
--input-file=url012/url012-$input.txt &